apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dsc-tenant-ui-access
  namespace: {{ .Name }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: monitoring
  podSelector:
    matchLabels:
      app: minio
  policyTypes:
  - Ingress